poll_interval_secs = 60

channels = [
  { platform = "youtube", channel_id = "@IsakiRiona",      name = "響咲リオナ" },
  { platform = "youtube", channel_id = "@ShirakamiFubuki", name = "白上フブキ" },
  { platform = "youtube", channel_id = "@kazamairoha",     name = "風間いろは" },
  { platform = "youtube", channel_id = "@MizumiyaSu",     name = "水宮樞" },
  { platform = "youtube", channel_id = "@TokoyamiTowa",     name = "常闇トワ" },
  # { platform = "bilibili", channel_id = "31936989",   name = "TestBilibili" },
  # { platform = "bilibili", channel_id = "1870886991", name = "迷湮" },
]

notifiers = [
  { type = "discord", endpoint = "https://discord.com/api/webhooks/1472157847042130011/nfp8aO_Q9MvMQitz5qunmgT9NXXstP0lHLL9mS47zZSlsgxDtwHjGX5vMOzydXlfjLpT" },
]
